name: CI Workflow

on:
  push:
    branches:
      - main  # Exécute le workflow sur un push vers la branche 'main'
  pull_request:
    branches:
      - main  # Exécute le workflow sur une PR vers 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu pour le job

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Configurer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Étape 4 : Lancer des tests (si applicable)
      - name: Run tests
        run: npm test
