name: Hello GitHub Actions

on:
  push:
    branches:
      - main  # Ce workflow sera déclenché sur un push vers la branche 'main'

jobs:
  say_hello:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu pour exécuter le job

    steps:
      # Étape 1 : Afficher "Hello" dans les logs
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"
